//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .//ConsoleApp2//ANTLR//BigIPConfigParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBigIPConfigParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class BigIPConfigParserBaseListener : IBigIPConfigParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConfig([NotNull] BigIPConfigParser.ConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConfig([NotNull] BigIPConfigParser.ConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.record"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecord([NotNull] BigIPConfigParser.RecordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.record"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecord([NotNull] BigIPConfigParser.RecordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.recordContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordContent([NotNull] BigIPConfigParser.RecordContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.recordContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordContent([NotNull] BigIPConfigParser.RecordContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.recordStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordStart([NotNull] BigIPConfigParser.RecordStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.recordStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordStart([NotNull] BigIPConfigParser.RecordStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.contentItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContentItem([NotNull] BigIPConfigParser.ContentItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.contentItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContentItem([NotNull] BigIPConfigParser.ContentItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.notRBrace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotRBrace([NotNull] BigIPConfigParser.NotRBraceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.notRBrace"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotRBrace([NotNull] BigIPConfigParser.NotRBraceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.notRecord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotRecord([NotNull] BigIPConfigParser.NotRecordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.notRecord"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotRecord([NotNull] BigIPConfigParser.NotRecordContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
