//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .//ConsoleApp2//ANTLR//BigIPConfigParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BigIPConfigParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IBigIPConfigParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConfig([NotNull] BigIPConfigParser.ConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.config"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConfig([NotNull] BigIPConfigParser.ConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.record"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecord([NotNull] BigIPConfigParser.RecordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.record"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecord([NotNull] BigIPConfigParser.RecordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.recordContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordContent([NotNull] BigIPConfigParser.RecordContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.recordContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordContent([NotNull] BigIPConfigParser.RecordContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.recordStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordStart([NotNull] BigIPConfigParser.RecordStartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.recordStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordStart([NotNull] BigIPConfigParser.RecordStartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.contentItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContentItem([NotNull] BigIPConfigParser.ContentItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.contentItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContentItem([NotNull] BigIPConfigParser.ContentItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.notRBrace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotRBrace([NotNull] BigIPConfigParser.NotRBraceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.notRBrace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotRBrace([NotNull] BigIPConfigParser.NotRBraceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BigIPConfigParser.notRecord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotRecord([NotNull] BigIPConfigParser.NotRecordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BigIPConfigParser.notRecord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotRecord([NotNull] BigIPConfigParser.NotRecordContext context);
}
